# Generated by Django 2.0.2 on 2018-02-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='namesys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accdb.Namesys'),
        ),
        migrations.AlterField(
            model_name='devtreeitem',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accdb.Dev'),
        ),
        migrations.AlterField(
            model_name='devtreeitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accdb.DevTreeItem'),
        ),
        migrations.AlterField(
            model_name='modedata',
            name='fullchan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accdb.FullChan'),
        ),
        migrations.AlterField(
            model_name='modemark',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accdb.Mode'),
        ),
        migrations.AlterField(
            model_name='sys',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accdb.Sys'),
        ),
    ]
