# Generated by Django 2.0.2 on 2018-03-15 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0002_auto_20180223_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='accdb.SysTest')),
            ],
            options={
                'db_table': 'systest',
            },
        ),
    ]
