# Generated by Django 2.0.2 on 2018-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0003_systest'),
    ]

    operations = [
        migrations.AddField(
            model_name='systest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='systest',
            name='devs',
            field=models.ManyToManyField(blank=True, to='accdb.Dev'),
        ),
        migrations.AddField(
            model_name='systest',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='systest',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
