# Generated by Django 2.0.2 on 2018-04-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0005_systestmp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SysTestMP',
            new_name='SysMP',
        ),
        migrations.RemoveField(
            model_name='systest',
            name='devs',
        ),
        migrations.RemoveField(
            model_name='systest',
            name='parent',
        ),
        migrations.AlterModelTable(
            name='sysmp',
            table='sys_mp',
        ),
        migrations.DeleteModel(
            name='SysTest',
        ),
    ]
