# Generated by Django 2.0.2 on 2018-07-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0006_auto_20180405_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullchan',
            name='access',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fullchan',
            name='protocol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mode',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
