# Generated by Django 2.0.2 on 2018-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0007_auto_20180704_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chan',
            name='access',
            field=models.CharField(default='rw', max_length=10),
        ),
    ]
