# Generated by Django 2.0.2 on 2018-07-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0008_auto_20180704_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chan',
            name='handle',
        ),
        migrations.AlterField(
            model_name='chan',
            name='access',
            field=models.CharField(default='r', max_length=10),
        ),
    ]
