# Generated by Django 2.0.2 on 2018-07-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0009_auto_20180705_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chan',
            name='saveble',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dev',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
