# Generated by Django 2.0.2 on 2018-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0010_auto_20180705_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullchan',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mode',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modedata',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
