# Generated by Django 2.0.2 on 2018-07-06 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0014_auto_20180705_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullchan',
            name='systems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
