# Generated by Django 2.0.2 on 2018-07-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0015_fullchan_systems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chan',
            old_name='saveble',
            new_name='savable',
        ),
    ]
