# Generated by Django 2.0.2 on 2018-07-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0016_auto_20180706_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullchan',
            name='cur_chan_name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
