# Generated by Django 2.0.2 on 2018-07-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0018_devtype_devmeta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devmeta',
            table='metadata',
        ),
    ]
