# Generated by Django 2.0.2 on 2018-07-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0019_auto_20180713_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevMeta',
            new_name='MetaData',
        ),
        migrations.RenameField(
            model_name='dev',
            old_name='devmeta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='devtype',
            old_name='devmeta',
            new_name='metadata',
        ),
    ]
