# Generated by Django 2.0.2 on 2018-07-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0020_auto_20180713_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modedata',
            name='fullchan',
        ),
        migrations.RemoveField(
            model_name='modedata',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='modemark',
            name='mode',
        ),
        migrations.DeleteModel(
            name='FullChan',
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.DeleteModel(
            name='ModeData',
        ),
        migrations.DeleteModel(
            name='ModeMark',
        ),
    ]
