# Generated by Django 2.0.2 on 2018-07-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0021_auto_20180714_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='namesys',
            name='def_soft',
            field=models.BooleanField(default=False),
        ),
    ]
