# Generated by Django 2.0.2 on 2018-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0022_namesys_def_soft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtype',
            name='soft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='namesys',
            name='soft',
            field=models.BooleanField(default=False),
        ),
    ]
