# Generated by Django 2.0.7 on 2018-07-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0023_auto_20180717_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmp',
            name='ord',
            field=models.IntegerField(),
        ),
    ]
