# Generated by Django 2.0.7 on 2018-08-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0024_auto_20180723_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sys',
            name='devs',
        ),
        migrations.RemoveField(
            model_name='sys',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Sys',
        ),
    ]
