# Generated by Django 2.0.7 on 2018-08-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0025_auto_20180802_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SysMP',
            new_name='Sys',
        ),
    ]
