# Generated by Django 2.0.7 on 2018-08-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0026_auto_20180802_1100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sys',
            table='sys',
        ),
    ]
