# Generated by Django 2.1.1 on 2018-09-02 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accdb', '0027_auto_20180802_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
