# Generated by Django 2.0.2 on 2018-07-09 15:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default='', max_length=50)),
                ('chan_name', models.CharField(default='', max_length=1024)),
                ('cur_chan_name', models.CharField(default='', max_length=1024)),
                ('access', models.CharField(default='', max_length=10)),
                ('namesys_id', models.IntegerField(default=0)),
                ('dev_id', models.IntegerField(default=0)),
                ('chan_id', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
                ('systems', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
            ],
            options={
                'db_table': 'fullchan',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1024)),
                ('author', models.CharField(default='', max_length=50)),
                ('stime', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mode',
            },
        ),
        migrations.CreateModel(
            name='ModeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utime', models.BigIntegerField()),
                ('value', models.FloatField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('fullchan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accmode.FullChan')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accmode.Mode')),
            ],
            options={
                'db_table': 'modedata',
            },
        ),
        migrations.CreateModel(
            name='ModeMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1024)),
                ('author', models.CharField(default='', max_length=100)),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accmode.Mode')),
            ],
            options={
                'db_table': 'modemark',
            },
        ),
    ]
