# Generated by Django 2.0.2 on 2018-07-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accmode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modedata',
            table='modedata_t',
        ),
    ]
