# Generated by Django 2.0.2 on 2018-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accmode', '0002_auto_20180713_0841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fullchan',
            unique_together={('chan_name', 'namesys_id', 'dev_id', 'chan_id')},
        ),
    ]
