# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdb', '0002_auto_20170724_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='admin_mail',
            field=models.CharField(default='emanov@inp.nsk.su', max_length=255),
        ),
    ]
