# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netdb', '0003_domain_admin_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='dns_options',
        ),
        migrations.RemoveField(
            model_name='net',
            name='dns_serial',
        ),
    ]
